ARG BUILD_TAG=latest
FROM nhais_nhais:${BUILD_TAG}
RUN pipenv install -d --ignore-pipfile
RUN printf "#!/bin/sh\npipenv run unittests && pipenv run componenttests && pipenv run inttests" > test.sh
RUN chmod +x test.sh
ENTRYPOINT ["/usr/src/app/nhais/test.sh"]
