ARG BUILD_TAG=latest
FROM local/nhais:${BUILD_TAG}
RUN pipenv install -d --ignore-pipfile
RUN printf "#!/bin/sh\npipenv run unittests && pipenv run componenttests && pipenv run inttests" > test.sh
RUN chmod +x test.sh
ENTRYPOINT ["/usr/src/app/test.sh"]
