ARG BUILD_TAG=nhais
FROM ${BUILD_TAG}_nhais:latest
RUN pipenv install -d --ignore-pipfile
RUN printf "#!/bin/sh\npipenv run unittests && pipenv run componenttests && pipenv run inttests" > test.sh
RUN chmod +x test.sh
ENTRYPOINT ["/usr/src/app/test.sh"]
