server:
  port: ${NHAIS_OUTBOUND_SERVER_PORT:8090}

logging:
  level:
    uk.nhs.digital.nhsconnect.nhais: ${NHAIS_LOGGING_LEVEL:INFO}
    org.apache.qpid.jms: WARN  # at INFO logs every 30 seconds

spring:
  main:
    allow-bean-definition-overriding: true
  jms:
    listener:
      acknowledge-mode: CLIENT

management:
  endpoints:
    web:
      base-path: /
      path-mapping.health: healthcheck
      exposure:
        include: info, health, metrics
  health:
    mongo:
      enabled: true
nhais:
  amqp:
    brokers: ${NHAIS_AMQP_BROKERS:amqp://localhost:5672}
    meshOutboundQueueName: ${NHAIS_MESH_OUTBOUND_QUEUE_NAME:nhais_responder_mesh_outbound}
    meshInboundQueueName: ${NHAIS_MESH_INBOUND_QUEUE_NAME:nhais_responder_mesh_inbound}
    gpSystemInboundQueueName: ${NHAIS_GP_SYSTEM_INBOUND_QUEUE_NAME:nahis_responder_gp_system_inbound}
    exchange: amq.direct
    username: ${NHAIS_AMQP_USERNAME:}
    password: ${NHAIS_AMQP_PASSWORD:}
    maxRedeliveries: ${NHAIS_AMQP_MAX_REDELIVERIES:3}
  mongodb:
    uri: ${NHAIS_MONGO_URI:mongodb://localhost:27017}
    database: ${NHAIS_MONGO_DATABASE_NAME:nhais_responder}
    host: ${NHAIS_MONGO_HOST:}
    port: ${NHAIS_MONGO_PORT:}
    username: ${NHAIS_MONGO_USERNAME:}
    password: ${NHAIS_MONGO_PASSWORD:}
    options: ${NHAIS_MONGO_OPTIONS:}
    autoIndexCreation: ${NHAIS_MONGO_AUTO_INDEX_CREATION:true}
  mesh:
    mailboxId: ${NHAIS_MESH_MAILBOX_ID:nhais_mailbox} #defaults below are used by fake-mesh
    mailboxPassword: ${NHAIS_MESH_MAILBOX_PASSWORD:password}
    sharedKey: ${NHAIS_MESH_SHARED_KEY:SharedKey}
    host: ${NHAIS_MESH_HOST:https://localhost:8829/messageexchange/} #local fake-mesh default endpoint
    endpointCert: ${NHAIS_MESH_ENDPOINT_CERT:-----BEGIN CERTIFICATE-----
      MIIFXzCCA0egAwIBAgIJALRbCSor9bEbMA0GCSqGSIb3DQEBCwUAMEUxCzAJBgNV
      BAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBX
      aWRnaXRzIFB0eSBMdGQwIBcNMTYwNDIwMTczOTA5WhgPMjIxNjAzMDMxNzM5MDla
      MEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJ
      bnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAw
      ggIKAoICAQDTHtXZykS5dsvFvhMWKB43p79NWJfHgH0sy4fDAQ1fU/lXc7kzR398
      sIWu67l1Tc9YqhTatPNSR+WPlc7O7bEB+1iLcoMzNFHawHLGOPFv+owjJsY3XMLV
      rOUPOpzT+ggaieI+FBxx0PIDfleRiTdkAtozC5wKDxEJtrpt4blMMit7VaeTp7dX
      ryJv1VAq034wjLzLjBI2l9H7Gx+JVCGtrxTxwDZrpoIdkJ7uCxOdO3bwpT2fvR8O
      RwmefC90q25sabeIodJxu2iqqRawHtaQ7g4WEimK1ed4hUoyOkxwtjfYV26vRXUP
      vJlTuoh3FhHZw5xAODBt+fMqJFjPlAYfCtMkXVNflu5ObTrQ5iQme40Ugbh3rSNE
      fQV68D6Qs9Bfs9EWMBx3h8PsLg7WCbaKhcm0oMavHXr12lH/z/nCf+cU+61U1yJ+
      Bn9g2Fn8iEb7b4J3qpQ+Cxf/pYknrXsgYY4p8j0EkQgBZDoHr7Tgb+koUOcn1InK
      NQLX2KV7MTe9P7ikn/kbE+HpW5bCL+N2KETV9qlqJ0mUR2H5+eaX+yme2Af0afFZ
      Z9rb97jzC9Elad3F6NK7Jdr6u3cPKIaU3qbuYDq3MxdtMGjiWyYRzixofpMgUqYm
      8EEv6GsT+eZNY+rhlyUkEou6upgOkLmZcNsbEM/K+JJm0bW87YoVBwIDAQABo1Aw
      TjAdBgNVHQ4EFgQUXxJ+6UmJ4cVNqXurwQJeyQALP4YwHwYDVR0jBBgwFoAUXxJ+
      6UmJ4cVNqXurwQJeyQALP4YwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOC
      AgEAmrJdePkitQtZmhopjnw11eT0WmvZnZfPDccm8LJ8uevQfHKdM5uruDGeE0r5
      SbUGuxC08Bs42ZNnqbXsbSzK7piHBfwG95VYC9knfBBg2Gv9EDKSJnr8NXdDyJeF
      caycrkFeGkdRal3bCfXO3rHQiMtukFG+x/OzD9gjEPEfmbBXC/gOesWJNFmS4doG
      +A4lAIXEbvDYdlzH/jh9C26t8LWwRirL9Hn6fHQbN4ywDH4n3FRvSElwH/uk/mEv
      4ksPphrAV760Rxsjy6XM2+IwFs1BrQVkPKT91WirFampmvsKModqhXJPb0SPLdd0
      G4sfyeiRzbzDjiq4igvD1HLIulPrbkdpLNUOsaSL56xE19FpHjl95OI9leKQeUMd
      No3A+gh00sBCYZvhHXCPVACQGOke8JeChxBmqWWuOdBXyXyE9iSZtN4SqNhWjGTQ
      97cqxZ4zgzmvb5FaGyG6ZmlWjCpkwNpbETp6CmqqN4sr//QnY+fc/6k5E3V31JWu
      lB6mv/JlORiEnDZjP6fO1L7yEvvc1vMlMMDCfNLbU5sdmp3LouR1Yf7uMzGzVL8r
      MsL1ds0kLcY9oQlduXOumM/bj+0hJTHxc06tr9ilzDAgQ+m48+xLxa6+X27m5pnl
      W/JNIRmhLoeFNGNh8HvhI2PwOCsFiqT1rrCaUtusTyH0Ggs=
      -----END CERTIFICATE-----}
    endpointPrivateKey: ${NHAIS_MESH_ENDPOINT_PRIVATE_KEY:-----BEGIN RSA PRIVATE KEY-----
      MIIJKQIBAAKCAgEA0x7V2cpEuXbLxb4TFigeN6e/TViXx4B9LMuHwwENX1P5V3O5
      M0d/fLCFruu5dU3PWKoU2rTzUkflj5XOzu2xAftYi3KDMzRR2sByxjjxb/qMIybG
      N1zC1azlDzqc0/oIGoniPhQccdDyA35XkYk3ZALaMwucCg8RCba6beG5TDIre1Wn
      k6e3V68ib9VQKtN+MIy8y4wSNpfR+xsfiVQhra8U8cA2a6aCHZCe7gsTnTt28KU9
      n70fDkcJnnwvdKtubGm3iKHScbtoqqkWsB7WkO4OFhIpitXneIVKMjpMcLY32Fdu
      r0V1D7yZU7qIdxYR2cOcQDgwbfnzKiRYz5QGHwrTJF1TX5buTm060OYkJnuNFIG4
      d60jRH0FevA+kLPQX7PRFjAcd4fD7C4O1gm2ioXJtKDGrx169dpR/8/5wn/nFPut
      VNcifgZ/YNhZ/IhG+2+Cd6qUPgsX/6WJJ617IGGOKfI9BJEIAWQ6B6+04G/pKFDn
      J9SJyjUC19ilezE3vT+4pJ/5GxPh6VuWwi/jdihE1fapaidJlEdh+fnml/spntgH
      9GnxWWfa2/e48wvRJWndxejSuyXa+rt3DyiGlN6m7mA6tzMXbTBo4lsmEc4saH6T
      IFKmJvBBL+hrE/nmTWPq4ZclJBKLurqYDpC5mXDbGxDPyviSZtG1vO2KFQcCAwEA
      AQKCAgEAqDsXD6BFWUCXqjAHR42aXqEWKM0izT/O/2YD/dkVzdO9iflWJ82egj6r
      mDKQqy/gvPdy/MBacEOIYv1uOahgd4LREPWkJKZZX6YhD2GKyr9s8gnQw4bwXpKS
      SKtdEvFXicY7+VnPPMbSQwRnRTqBX/mB5FEo+z78RbBNKIhJPrVvvq0HhvqLd5zA
      JTtm0WmMUaWkP9KTJNuf4KfBXo4i9CLi3q1a8DdT0blPW8KJ063x3lreGy7500e6
      G4c7zY1ZxZwMOx0v857yDaQFxzwboIuBwAajAdXnyDr2X8Xi6aHaKFOriJEhcfPI
      flbSrYpxmQRtuyLLPKeDJB6ogmii4qCVcnotw9co1yz3nRXbPOaTw+pDg7ZZveDn
      02Ip+ayQFrQVzS9aZmZr4eR+Hh6681Ujng3Zrdp03rUXpQ1opyjN1K4rExIRjEiK
      Q9cP/0Y3LF5mpwfm0+SxdbZ6FAa57N5quSobNaWGTb1SYF1BtPf/B6s2RfUZOjhg
      pwKBF4fL/eHnCfqV8dWlOBs48TwdYrLxurOEGkqFicGdKGO8ayERHpmFD+V7YNbd
      PrwyoUbK9Jh8ApslRLTOBcDz+3Cx1oogDMHXkMy7FzvG6s54RgA0SS+SzsS5yMDP
      XF7iymVzdwDTeaA0y2lPgHD/nnVfwzZttXiRvLILOKTemp+NrPECggEBAPU6oyJO
      +zYeBoDs8aT0YU0OfyfUJa3ZKvIp0AZ8nKU/6otlPu/2gtoHrJfPo0XssczEs3py
      wMSX+WxNASKCVRtbqRWVJa/8tRf3YfDeUUrS1aWyD1UEQG6RwG+ACB4W0l+RRVhS
      YBgDyjivPy0OK2hm6T8ctoMWlVv76uhwWkfkFsIzLfQ8HEeySjMngxPW69lgw9/v
      Sl6fiMeWdsDtoHGqHqluMBLxvBuaLdaFpiNSP+npPweRkii01DWlMojpPWYDVpo5
      fx62qBUhk+SineYmzKfmUT972T4EHvK0WGSm3BKQB1K0H9wMlBJXXVaQMl0fQ/bw
      6AAwOugU/fqycX8CggEBANxkrhOMrc5x2Juvn6rzpdG1w29qKUWInpS8tvKdJ4fd
      5iT+A4y4a6rHLGxFQRWePNJ+6uqmy/zwr74BLineDc9slc51PRz/T9S6odAHDWIP
      X4qho8xfzzN8gSnjrc3TGlpnQAA5u8I/nggfzCUDBYNBmYai7mbuD2ckpRGKf2dr
      dNA77azK5n7HBJqS4dkCphnoSwZicmtsT94Ol6AbmIDkyyLfJ0uBuSPtjZj0rySu
      li/0oR6tilVgphvPKeuxcaD4YmA7S6MpIv8Kvl/8960Wh1qEDTDrAr7t7TU6mz9z
      5vc2rFix19WFDyeCfse6Igfcgg3Pge9l/yWHoVglkHkCggEAFtkBvf6R1Tby8Cwj
      T3UdY6qIGlPfttTW9X0DzrbpeVP9LEOgm4biJiI06GgGFEu7PRLOjggHAcoPCRIb
      mvV9rHDbzhD5U+49iSAZVfHArTH7idaPKyKcRjD6Nuk82GDT9Od6CIKURWiE/McH
      IdGCJdYAwUqRjqEaBVnxRvrAzpXnsOxHycuX7u4jj6SMx9psWvJzDXgj+7Dtc3sH
      UW5SVoS9GpgTjpBLMF8rCiOlmQDex5JdtvzPG0/NvbnIfY0NlWWWOgRFXb0y59Ub
      DGBCSeEvjC0fQMTvNqH3qDE5UxdgxbH5nLD/jub1HMha/+eraZWyJV3In8vekSTz
      jNn3TQKCAQByWtcsE6GXbeD7nxvU4wlWD97xL39ssd++w1CWAE8jo1KoPRjwajyL
      Zz84ipKjufBLNEmGKbfMbcJyb0BZvvshdnEgqBpmsl7kvVX6j7409E8ZqpdIEyp6
      x45pgtaK5o9U+x/tPgebWdEQ3Bbb2X6BxYb4og/bXoildxEjUd6bddkttvqy3rDM
      dU2BOtdu933iEXLkRC6kaJXkXWP1UnxF3PE+DdXgytWau8bt53/9I42QInl7ZoZR
      mI13/nz865xO7rJ0xi+P4GdlOFjhi2uj5v2iTMRfboGFOgULynYFbYkZGshAWT7p
      bloXoRFRZtYDiDn/Gn2MDztdaMuh5hPZAoIBAQDEASV+dXBNZOIxQ5IQVn6xMOTs
      kKiA539B0lD2CDJQI7UXeat1sJXHZx8QVodY1VwQCJW8u4XLxphgC1Wx9+EjXek8
      +C8OxuXZamXgRaGeCFn3Ev3XsQnRiDVJJZ34JuDBP+hcGIj4JPHQE9qEsPKRBkyJ
      yIBNWf7N1eRRn5h4cVMolnvbulEppXYTlKDKqYgrNecIESiWd8WHPeudkWLmDcfy
      +yLvICQmVjHWsNWD3uuT3gEGdeKDIzEnovXUmqhQE7N/YDupTv5hkh8hMKl12XGs
      3WJ4bVSmp3MOQ2EF4zrAl4fXEd4lS3JxKtzbHFbSogAmPFnuP8wIDWTDgfEq
      -----END RSA PRIVATE KEY-----}
    cypherToMailbox: ${NHAIS_MESH_CYPHER_TO_MAILBOX:XX11=gp_mailbox
      TES5=gp_mailbox
      YY21=gp_mailbox
      KC01=gp_mailbox
      WHI5=gp_mailbox
      SO01=gp_mailbox
      UNY5=gp_mailbox}
    scanMailboxIntervalInMilliseconds: ${NHAIS_SCAN_MAILBOX_INTERVAL_IN_MILLISECONDS:10000}
    scanMailboxDelayInSeconds: ${NHAIS_SCAN_MAILBOX_DELAY_IN_SECONDS:30}
  scheduler:
    enabled: ${NHAIS_SCHEDULER_ENABLED:true}
