server:
  port: 9999

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    uk.nhs.digital.nhsconnect.nhais: ${NHAIS_LOGGING_LEVEL:DEBUG}
    org.apache.qpid: DEBUG

nhais:
  amqp:
    brokers: ${NHAIS_AMQP_BROKERS:}
    meshOutboundQueueName: ${NHAIS_MESH_OUTBOUND_QUEUE_NAME:ptl_nhais_mesh_outbound}
    meshInboundQueueName: ${NHAIS_MESH_INBOUND_QUEUE_NAME:ptl_nhais_mesh_inbound}
    gpSystemInboundQueueName: ${NHAIS_GP_SYSTEM_INBOUND_QUEUE_NAME:ptl_nhais_gp_system_inbound}
    exchange: amq.direct
    username: ${NHAIS_AMQP_USERNAME:}
    password: ${NHAIS_AMQP_PASSWORD:}
    maxRedeliveries: ${NHAIS_AMQP_MAX_REDELIVERIES:3}
  mongodb:
    uri: ${NHAIS_MONGO_URI:mongodb://localhost:27017}
    database: ${NHAIS_MONGO_DATABASE_NAME:nhais}
    host: ${NHAIS_MONGO_HOST:}
    port: ${NHAIS_MONGO_PORT:}
    username: ${NHAIS_MONGO_USERNAME:}
    password: ${NHAIS_MONGO_PASSWORD:}
    options: ${NHAIS_MONGO_OPTIONS:}
    document-db-tls: ${NHAIS_MONGO_DOCUMENTDB_TLS_ENABLED:false}
    trust-store-path: ${NHAIS_MONGO_TRUST_STORE_PATH:}
    trust-store-password: ${NHAIS_MONGO_TRUST_STORE_PASSWORD:}
  test:
    hostAndPort: ${HOST_AND_PORT:localhost:8080}
