name: Publish Workflow
on:
  workflow_call:
    inputs:
      build-id:
        required: true
        type: string

jobs:
  build-and-publish-docker-image:
    name: Build & Publish Docker Image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 #5.1.1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: gp2gp_github_action_build_workflow
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build Docker Image
        run: |
          DOCKER_REGISTRY="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com"
          DOCKER_TAG="$DOCKER_REGISTRY/nhais:${{ inputs.build-id }}"
          echo "DOCKER_TAG=$DOCKER_TAG" >> $GITHUB_ENV

          # Build Image
          docker build -f ./Dockerfile -t $DOCKER_TAG .

      - name: Login to AWS ECR
        run: |
          DOCKER_REGISTRY="https://${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com"
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin $DOCKER_REGISTRY

      - name: Publish image to ECR
        run: docker push $DOCKER_TAG

      - name: Logout of AWS ECR (Clean up Credentials)
        if: always()
        run: |
          DOCKER_REGISTRY="https://${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com"
          docker logout $DOCKER_REGISTRY