name: Test Workflow
on:
  push:
    branches:
      - test-sbom

jobs:
  checkstyle:
    name: Checkstyle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 21 LTS
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Checkstyle
        run: ./gradlew checkStyleMain checkstyleTest checkstyleIntTest

      - name: Collect Artifacts
        if: always()
        run: |
          mkdir -p artifacts
          cp -r ./build/reports ./artifacts

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: 'Checkstyle Reports'
          path: ./artifacts/**
          compression-level: 9

      - name: Temporary Artifacts Cleanup
        run: rm -rf ./artifacts

  run-sbom-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x ./scripts/sbom-generator.sh

      - name: Run the shell script
        run: ./scripts/sbom-generator.sh

      - name: Collect Artifacts
        run: |
          mkdir -p artifacts
          pwd
          ls
          
          cp -r ./sbom-spdx.json ./artifacts

      - name: Upload SBOM Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SBOM Report
          path: ./artifacts/**
          compression-level: 9

      - name: Temporary Artifacts Cleanup
        if: always()
        run: rm -rf ./artifacts


  unit-tests:
    name: Unit Tests
    needs: [ checkstyle ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Java 21
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 #4.7.1
        with:
          java-version: 21
          distribution: temurin

      - name: Execute Unit Tests
        run: ./gradlew test --parallel --build-cache

      - name: Collect Artifacts
        if: always()
        run: |
          mkdir -p artifacts
          cp -r ./build/reports ./artifacts

      - name: Upload Artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        if: always()
        with:
          name: Unit Test Report
          path: ./artifacts/**
          compression-level: 9

      - name: Test Job Summary
        if: always()
        uses: test-summary/action@31493c76ec9e7aa675f1585d3ed6f1da69269a86 #v2.4.0
        with:
          paths: ./build/test-results/test/TEST-*.xml

      - name: Temporary Artifacts Cleanup
        run: rm -rf ./artifacts

  component-tests:
    name: Component Tests
    needs: [ checkstyle ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Java 21
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 #4.7.1
        with:
          java-version: 21
          distribution: temurin

      - name: Execute Component Tests
        run: ./gradlew componentTest --build-cache

      - name: Collect Artifacts
        if: always()
        run: |
          mkdir -p artifacts
          cp -r ./build/reports ./artifacts

      - name: Upload Artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        if: always()
        with:
          name: Component Test Report
          path: ./artifacts/**
          compression-level: 9

      - name: Test Job Summary
        if: always()
        uses: test-summary/action@31493c76ec9e7aa675f1585d3ed6f1da69269a86 #v2.4.0
        with:
          paths: ./build/test-results/componentTest/TEST-*.xml

      - name: Temporary Artifacts Cleanup
        run: rm -rf ./artifacts

  integration_tests:
    name: Integration Tests
    needs: [ checkstyle ]
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 #4.7.1
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Required Docker Images
        run: docker compose up mongodb activemq fake-mesh -d

      - name: Execute Integration Tests
        run: ./gradlew integrationTest

      - name: Dump Docker Logs
        if: always()
        run: |
          mkdir -p ./logs
          container_names=$(docker ps -a --format '{{.Names}}')
          for container in $container_names; do
              docker logs "$container" > ./logs/"$container".log
              echo "Logs saved for container: $container"
          done
        shell: bash

      - name: Collect Artifacts
        if: always()
        run: |
          mkdir -p artifacts
          cp -r ./build/reports ./artifacts
          cp -r ./logs ./artifacts

      - name: Upload Artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        if: always()
        with:
          name: Integration Test Report & Docker Logs
          path: ./artifacts/**
          compression-level: 9

      - name: Test Job Summary
        if: always()
        uses: test-summary/action@31493c76ec9e7aa675f1585d3ed6f1da69269a86 #v2.4.0
        with:
          paths: ./build/test-results/integrationTest/TEST-*.xml

      - name: Stop Docker Dependencies
        if: always()
        run: docker compose down --rmi=local --remove-orphans

      - name: Temporary Artifacts Cleanup
        run: rm -rf ./artifacts
